name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies and build CSS (root)
        run: |
          npm ci
          npm run build-css

      - name: Install dependencies and build Storybook (app)
        run: |
          cd app
          npm ci
          npm run build-storybook
          ls -la # List the contents of the current directory

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          BRANCH: main # The branch the action should deploy to.
          FOLDER: ./app/.nuxt-storybook # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
